package ch.jmanagr.lib;

/**
 * Status-Codes for different actions
 */
public enum STATUS_CODE
{
	OK(1),
	FAIL(2),
	ALREADY_EXISTS(4),
	FAIL_WITH_UNKOWN_REASON(8),
	NAME_INVALID(16),
	PASSWORD_INVALID(32),
	PASSWOR_MISSMATCH(64),
	NOT_AUTHORIZED(128),
	USERNAME_INVALID(256),
	NO_CONNECTION_TO_SERVER(512),
	ACCESS_DENIED(1024),
	ACCESS_BLOCKED(2048),
	NOT_ENOUGH_PRIVILEGES(4096),
	CANNOT_DELETE_OBJECT(8192);

	public final int value;

	private STATUS_CODE(int i)
	{
		value = i;
	}
}
